name: refresh-resolvers

on: workflow_dispatch

jobs:
  resfresh-list:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout DNS Validator
        uses: actions/checkout@v2
        with:
          repository: 'vortexau/dnsvalidator'
          path: dnsvalidator
    
      - name: Install DNS Validator
        run: |
          cd dnsvalidator
          python3 setup.py install
    
      - name: Generate new resolvers
        run: |
          dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 --silent >  ~/resolvers.txt
          dnsvalidator -tL ~/resolvers.txt -threads 20 --silent > ~/resolvers2.txt
          dnsvalidator -tL ~/resolvers2.txt -threads 20 --silent > ~/resolvers3.txt
    
      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # - name: Move up directory
      #   run: |
      #     mv resolvers.txt ..
      #     cd ..
      
      - name: Commit changes
        run: |
          mv ~/resolvers3.txt ./resolvers.txt
          git config --local user.email "edu4rdshl@protonmail.com"
          git config --local user.name "Edu4rdSHL"
          git add resolvers.txt
          git commit -m "${NOW} update."
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
